config/routes.rb
Rails.application.routes.draw do
  resources :accounts
  get 'visitors/index'

  devise_for :users
  resources :users
  root to: 'visitors#index'
end

app/models/account.rb
class Account < ApplicationRecord

  def generate_subdomain
  	resto_name.parameterize.gsub(/-/,'')
  end

  def generate_password
  	"#{generate_subdomain}#{id}"
  end
    
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        if user_signed_in?
          @account.update_attributes(:user_id => current_user.id, :subdomain => @account.generate_subdomain)
        else
          @new_user = User.create(:email => @account.resto_mail, :password => @account.generate_password, :password_confirmation => @account.generate_password)
          @account.update_attributes(:subdomain => @account.generate_subdomain, :user_id => @new_user.id)          
        end
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:resto_name, :resto_mail, :user_id, :subdomain)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
	def index
		@users = User.all		
	end

	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
    @user = User.find(params[:id])
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

private
   
  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/accounts/_form.html.erb
<%= simple_form_for(@account) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :resto_name %>
    <%= f.input :resto_mail %>
    <%= f.input :user_id %>
    <%= f.input :subdomain %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<%= link_to 'New Account', new_account_path, class: "btn btn-default btn-block" %>


<ul class="list-group">
    <li class="list-group-item list-group-item-info">
      <div class="row">
        <div class="col-md-3">
          Resto name
        </div>
        <div class="col-md-3">
          Resto mail
        </div>
        <div class="col-md-1">
          User
        </div>
        <div class="col-md-3">
          Subdomain
        </div>
        <div class="col-md-2">
          
        </div>        
      </div>
    </li>

      <% @accounts.each do |account| %>

    <li class="list-group-item">
      <div class="row">
        <div class="col-md-3">
          <%= account.resto_name %>
        </div>
        <div class="col-md-3">
          <%= account.resto_mail %>
        </div>
        <div class="col-md-1">
          <%= account.user_id %>
        </div>
        <div class="col-md-3">
          <%= account.subdomain %>
        </div>
        <div class="col-md-2">
          <%= link_to 'Show', account %><br>
          <%= link_to 'Edit', edit_account_path(account) %>
          <%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>      
      </div>      
    </li>

  <% end %>
</ul>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Resto name:</strong>
  <%= @account.resto_name %>
</p>

<p>
  <strong>Resto mail:</strong>
  <%= @account.resto_mail %>
</p>

<p>
  <strong>User:</strong>
  <%= @account.user_id %>
</p>

<p>
  <strong>Subdomain:</strong>
  <%= @account.subdomain %>
</p>

<p>
  <strong>Generate Subdomain:</strong>
  <%= @account.generate_subdomain %>
</p>

<p>
  <strong>Generate Password:</strong>
  <%= @account.generate_password %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Speku</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :email %>

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/users/index.html.erb
index.html.erb

app/views/users/show.html.erb
show.html.erb

app/views/visitors/index.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>